build:
  stage: test
  script:
    - mvn --batch-mode org.jacoco:jacoco-maven-plugin:prepare-agent verify -U -Dmaven.test.failure.ignore=true
    - sonar-scanner
    - sh ci/sonar_notify.sh
  only:
    - 5_3_unit_test
  tags:
    - dt-insight-engine