UPDATE schedule_dict t
SET depend_name = '0,1'
WHERE dict_code = 'flink_version' and dict_name = '1.12';

INSERT INTO schedule_dict(dict_code, dict_name, dict_value, dict_desc, type, sort, data_type, depend_name, is_default, gmt_create, gmt_modified, is_deleted)
VALUES ('typename_mapping', 'flink112-standalone', '-120', null, 6, 0, 'LONG', '', 0, now(),now(),0);

INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'jobmanager.rpc.address', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'jobmanager.rpc.port', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'rest.port', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'prometheusHost', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'prometheusPort', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'high-availability', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'high-availability.zookeeper.quorum', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'high-availability.zookeeper.path.root', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'high-availability.storageDir', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'high-availability.cluster-id', '', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'flinkLibDir', '/data/insight_plugin/flink112_lib', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'flinkxDistDir', '/data/insight_plugin112/flinkxplugin', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'remoteFlinkxDistDir', '/data/insight_plugin112/flinkxplugin', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'pluginLoadMode', 'classpath', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 1, 'clusterMode', 'standalone', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, 'INPUT', 0, 'state.backend', 'jobmanager', null, null, null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, '', 0, 'false', 'false', null, 'metrics.reporter.promgateway.deleteOnShutdown', null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, '', 0, 'true', 'true', null, 'metrics.reporter.promgateway.deleteOnShutdown', null, null, now(),now(),0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, '', 0, 'false', 'false', null, 'metrics.reporter.promgateway.randomJobNameSuffix', null, null, now(),now(), 0);
INSERT INTO console_component_config ( cluster_id, component_id, component_type_code, type, required, `key`, value, `values`, dependencyKey, dependencyValue, `desc`, gmt_create, gmt_modified, is_deleted) VALUES ( -2, -120, 20, '', 0, 'true', 'true', null, 'metrics.reporter.promgateway.randomJobNameSuffix', null, null, now(),now(), 0);