INSERT INTO `console_component_config` (`cluster_id`, `component_id`, `component_type_code`, `type`, `required`, `key`, `value`, `values`, `dependencyKey`, `dependencyValue`, `desc`, `gmt_create`, `gmt_modified`, `is_deleted`) VALUES
  (-2, -108, 1, 'INPUT', 1, 'spark.client.leader.election.type', 'zookeeper', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.client.leader.election.type', 'zookeeper', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.client.leader.election.type', 'zookeeper', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.driver.userClassPathFirst', 'true', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.driver.userClassPathFirst', 'true', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.driver.userClassPathFirst', 'true', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.zookeeper.url', '', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.zookeeper.url', '', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.zookeeper.url', '', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.zookeeper.namespace', 'spark/2.1.3', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.zookeeper.namespace', 'spark/2.4.8', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.zookeeper.namespace', 'spark/3.2.2', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.thrift.server.start.port', '20000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.thrift.server.start.port', '20000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.thrift.server.start.port', '20000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.thrift.server.port.retries', '1000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.thrift.server.port.retries', '1000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.thrift.server.port.retries', '1000', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.thrift.server.min.worker.threads', '5', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.thrift.server.min.worker.threads', '5', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.thrift.server.min.worker.threads', '5', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -108, 1, 'INPUT', 1, 'spark.thrift.server.max.worker.threads', '300', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -130, 1, 'INPUT', 1, 'spark.thrift.server.max.worker.threads', '300', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0),
  (-2, -132, 1, 'INPUT', 1, 'spark.thrift.server.max.worker.threads', '300', NULL, 'deploymode$perjob', NULL, NULL, now(), now(), 0);

