package com.dtstack.engine.dao;

import com.dtstack.engine.api.domain.AlertAlarmModel;
import com.dtstack.engine.po.AlertAlarm;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AlertAlarmDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm
     *
     */
    int deleteByPrimaryKey(Long id);

    Integer deleteByIds(@Param("ids") List<Long> ids);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm
     *
     */
    int insert(AlertAlarm record);

    /**
     * 通过项目查询id
     */
    List<AlertAlarm> selectIdByProjectId(@Param("projectId") Long projectId,@Param("nameList")List<String> nameList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm
     *
     */
    AlertAlarm selectByPrimaryKey(@Param("id") Long id);

    /**
     * count by alertAlarmModel
     */
    Long countByModel(@Param("model") AlertAlarmModel model);

    /**
     * page by alertAlarmModel
     */
    List<AlertAlarm> selectPageByModel(@Param("model") AlertAlarmModel model);

    /**
     * 批量获得告警规则
     */
    List<AlertAlarm> selectByIds(@Param("alarmIds") List<Long> alarmIds,
                                 @Param("appType")Integer appType,
                                 @Param("projectId")Long projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm
     *
     */
    int updateByPrimaryKeySelective(AlertAlarm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm
     *
     */
    int updateByPrimaryKey(AlertAlarm record);

    /**
     * 更新状态
     */
    Integer updateOpenStatusById(@Param("id") Long id, @Param("openStatus") Integer openStatus);


    List<AlertAlarm> scanningAlertAlarmByIdLimit(@Param("startId") Long id, @Param("alarmType") Integer alarmType, @Param("limit") Integer limit);

    String selectByProjectIdAndName(@Param("projectId") Long projectId, @Param("name") String name);


    List<AlertAlarm> listByProjectIdAndAppTypeAndScope(@Param("projectId") Long projectId,
                                                       @Param("appType")Integer appType,
                                                       @Param("scopes") List<Integer> scopes);

}