package com.dtstack.engine.dao;

import com.dtstack.engine.po.AlertAlarmRule;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Auther: dazhi
 * @Date: 2022/5/6 1:44 PM
 * @Email: dazhi@dtstack.com
 * @Description:
 */
public interface AlertAlarmRuleDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm_rule
     */
    int deleteByPrimaryKey(@Param("id") Long id);

    /**
     * deleteByAlertId
     */
    int deleteByAlertId(@Param("alarmId") Long alarmId);

    /**
     *
     */
    int deleteByAlertIds(@Param("alarmIds") List<Long> alarmIds,
                         @Param("businessType") Integer businessType,
                         @Param("businessIds") List<Long> businessIds);

    int deleteByCondition(@Param("alarmIds") List<Long> alarmIds,
                          @Param("businessTypes") List<Integer> businessTypes,
                          @Param("businessIds") List<Long> businessIds);

    /**
     * 批量插入规则
     */
    Integer batchInsert(@Param("alertAlarmRules") List<AlertAlarmRule> alertAlarmRules);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm_rule
     */
    AlertAlarmRule selectByPrimaryKey(Integer id);

    /**
     * select AlarmId by BusinessType And BusinessId
     */
    List<Long> selectAlarmByBusinessTypeAndBusinessId(@Param("businessType") Integer businessType, @Param("businessIds") List<Long> businessIds);

    /**
     * select rule by alarmid
     */
    List<AlertAlarmRule> selectByAlarmIds(@Param("alertAlarmIds") List<Long> alertAlarmIds,@Param("businessType") Integer businessType);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm_rule
     */
    int updateByPrimaryKeySelective(AlertAlarmRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_alarm_rule
     */
    int updateByPrimaryKey(AlertAlarmRule record);


    void deleteByIds(@Param("ids") List<Long> ids);
}
